let a=10

console.log(a)

try{
    console.log(b)
}catch(err)
{
    console.log(`Error occured ${err}`)
}

console.log('Hello world')